deployment:
  - name: blue
    replicas: 1
    color: blue
    weight: 10

  - name: green
    replicas: 1
    color: green
    weight: 15

  - name: yellow
    replicas: 1
    color: yellow
    weight: 25